---
clusterGroup:
  name: resilient
  isHubCluster: false

  argoCD:
    resourceTrackingMethod: annotation

  namespaces:
    openshift-cnv: {}
    openshift-storage: {}
    policies: {}
    gitops-vms: {}
    external-dns-operator: {}
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    openshift-adp:
      operatorGroup: true
      targetNamespaces:
        - openshift-adp
    openshift-workload-availability:
      operatorGroup: true
      targetNamespaces: []

  subscriptions:
    openshift-virtualization:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      channel: stable

    external-dns:
      name: external-dns-operator
      namespace: external-dns-operator
      channel: stable-v1

    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1

    node-health-check:
      name: node-healthcheck-operator
      namespace: openshift-workload-availability
      channel: stable

    self-node-remediation:
      name: self-node-remediation
      namespace: openshift-workload-availability
      channel: stable

    openshift-data-foundation:
      name: odf-operator
      namespace: openshift-storage

    openshift-oadp:
      name: redhat-oadp-operator
      namespace: openshift-adp
      channel: stable

  argoProjects:
    - resilient

  imperative:
    jobs: []

  applications:
    ensure-openshift-console-plugins:
      name: ensure-openshift-console-plugins
      namespace: openshift-console
      argoProject: resilient
      chart: ensure-openshift-console-plugins
      chartVersion: 0.1.*
      extraValueFiles:
        - '$patternref/overrides/values-console-plugins-spokes.yaml'

    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      argoProject: resilient
      chart: openshift-external-secrets
      chartVersion: 0.0.*

    openshift-cnv:
      name: openshift-cnv
      namespace: openshift-cnv
      argoProject: resilient
      chart: openshift-virtualization-instance
      chartVersion: 0.1.*

    odf:
      name: odf
      namespace: openshift-storage
      argoProject: resilient
      chart: openshift-data-foundations
      chartVersion: 0.2.*
      extraValueFiles:
        - '$patternref/overrides/values-odf-chart.yaml'

    node-health-check-operator:
      name: node-health-check-operator
      namespace: openshift-workload-availability
      argoProject: resilient
      chart: node-health-check-operator
      chartVersion: 0.1.*

    external-dns-operator:
      name: external-dns-operator
      namespace: external-dns-operator
      argoProject: resilient
      chart: external-dns-operator
      chartVersion: 0.1.*

    adp-data-protection:
      name: adp-data-protection-application
      namespace: openshift-adp
      argoProject: resilient
      repoURL: https://github.com/validatedpatterns/oadp-data-protection-application-chart.git
      chartVersion: main
      path: "."

  managedClusterGroups: []
