- name: Set aws region
  ansible.builtin.set_fact:
    aws_region: "{{ vars[vpc.value.region ~ '_aws_region'] }}"


- name: debug
  debug:
    msg: "will pair vpc {{ vpc.value.vpc_id }} to {{ ec2_vpcs[item.name].vpc_id }} in region: {{ vars[ec2_vpcs[item.name].region ~ '_aws_region'] }}"
  loop: "{{ vpc.value.peer }}"
  when: vpc.value.peer | length > 0


- name: Create intra-region EC2 VPC Peering Connection
  amazon.aws.ec2_vpc_peering:
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc.value.vpc_id }}"
    peer_vpc_id: "{{ ec2_vpcs[item.name].vpc_id }}"
    peer_region: "{{ vars[ec2_vpcs[item.name].region ~ '_aws_region'] }}"
    state: "present"
  register: vpc_peer_result
  loop: "{{ vpc.value.peer }}"
  when: vpc.value.peer | length > 0


- name: Build a list of updates
  ansible.builtin.set_fact:
    update_list: "{{ update_list + update }}"
  loop: "{{ vpc_peer_result.results }}"
  vars:
    update_list: []
    update:
    - path: ec2_vpcs[{{ vpc.key }}].peer[{{ index }}].vpc_peer_id
      value: "{{ item.vpc_peering_connection.vpc_peering_connection_id }}"
    index: "{{ vpc.value.peer | ansible.utils.index_of('eq', item.item ) }}"

- name: Make the updates (unroll the loop)
  ansible.utils.update_fact:
    updates: "{{ update_list }}"
  register: updated

- name: Update fact in place
  ansible.builtin.set_fact:
    ec2_vpcs: "{{ updated.ec2_vpcs }}"

- name: Accept EC2 VPC Peering Connection from peer region
  amazon.aws.ec2_vpc_peering:
    region: "{{ item.vpc_peering_connection.accepter_vpc_info.region }}"
    peering_id: "{{ item.vpc_peering_connection.vpc_peering_connection_id }}"
    state: "accept"
  loop: "{{ vpc_peer_result.results }}"

- name: Set up route table from vpc to peered vpc 
  amazon.aws.ec2_vpc_route_table:
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc.value.vpc_id }}"
    route_table_id: "{{ vpc.value.route_table_id }}"
    lookup: id
    purge_routes: false
    routes:
      - dest: "{{ ec2_vpcs[item.name].cidr }}"
        vpc_peering_connection_id: "{{ item.vpc_peer_id }}"
    profile: "{{ aws_profile }}"
  loop: "{{ ec2_vpcs[vpc.key].peer }}"
  when: ec2_vpcs[vpc.key].peer | length > 0

- name: Set up route table from peered vpc to vpc 
  amazon.aws.ec2_vpc_route_table:
    region: "{{ vars[ec2_vpcs[item.name].region ~ '_aws_region'] }}"
    vpc_id: "{{ ec2_vpcs[item.name].vpc_id }}"
    route_table_id: "{{ ec2_vpcs[item.name].route_table_id }}"
    lookup: id
    purge_routes: false
    routes:
      - dest: "{{ vpc.value.cidr }}"
        vpc_peering_connection_id: "{{ item.vpc_peer_id }}"
    profile: "{{ aws_profile }}"
  loop: "{{ ec2_vpcs[vpc.key].peer }}"
  when: ec2_vpcs[vpc.key].peer | length > 0
